docs/basics.md
docs/porting-a-v2-ea-to-v3.md

Fix: typos

---

src/adapter/price.ts
src/adapter/types.ts

[PDI-198](https://smartcontract-it.atlassian.net/browse/PDI-198)
[PDI-198]: https://smartcontract-it.atlassian.net/browse/PDI-198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

enforce SingleNumberResultResponse for PriceEndpoint

---

docs/porting-a-v2-ea-to-v3.md

[PDI-199](https://smartcontract-it.atlassian.net/browse/PDI-199)
[PDI-199]: https://smartcontract-it.atlassian.net/browse/PDI-199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update ea v2 to v3 migration guide

---

src/adapter/basic.ts
src/adapter/endpoint.ts
src/cache/index.ts
src/cache/response.ts
src/transports/metrics.ts
src/validation/index.ts
test/cache/cache-key.test.ts
test/cache/helper.ts
test/cache/redis.test.ts
test/metrics/metrics.test.ts

Added the adapter name to the cache key to avoid collisions between adapters when using Redis.

Add adapter name to cache key

---

src/transports/websocket.ts

Tiny fix to address the connection parameter to the open handler now that the handlers are built with the connection isolated from the class

Connection parameter fix

---

src/metrics/index.ts
src/transports/abstract/subscription.ts
test/metrics/warmer-metrics.test.ts
test/metrics/ws-metrics.test.ts

[PDI-2046](https://smartcontract-it.atlassian.net/browse/PDI-2046)
[PDI-2046]: https://smartcontract-it.atlassian.net/browse/PDI-2046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add transport name to background metrics

---

src/cache/local.ts
src/cache/redis.ts
test/cache/local.test.ts
test/metrics/redis-metrics.test.ts
test/util.ts

[PDI-2044](https://smartcontract-it.atlassian.net/browse/PDI-2044)
[PDI-2044]: https://smartcontract-it.atlassian.net/browse/PDI-2044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Functional/manual tests were performed, both for local and redis to make sure that everything works as expected

skip overwriting successful cache entries with errors

---

src/cache/metrics.ts
src/metrics/index.ts
src/transports/abstract/subscription.ts
test/metrics/warmer-metrics.test.ts
test/metrics/ws-metrics.test.ts

[PDI-1964](https://smartcontract-it.atlassian.net/browse/PDI-1964)
[PDI-1964]: https://smartcontract-it.atlassian.net/browse/PDI-1964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove unused labels from v3 metrics

---

src/config/index.ts
src/transports/websocket.ts
test/transports/websocket.test.ts

[PDI-2042](https://smartcontract-it.atlassian.net/browse/PDI-2042)
[PDI-2042]: https://smartcontract-it.atlassian.net/browse/PDI-2042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add new testcases for WS connection

---

src/config/index.ts
src/util/requester.ts

Added TIME_TO_SLEEP_MS to BaseSettingsDefinition, for setting a custom delay between HTTP requests

Add TIME_TO_SLEEP_MS to BaseSettingsDefinition

---

src/adapter/basic.ts
src/adapter/endpoint.ts
src/cache/response.ts
src/transports/websocket.ts
src/validation/index.ts
test/adapter.test.ts
test/cache/cache-key.test.ts
test/cache/helper.ts
test/cache/redis.test.ts
test/config.test.ts
test/error.test.ts
test/index.test.ts
test/metrics/metrics.test.ts
test/price.test.ts
test/rate-limit-config.test.ts
test/subscription-set/subscription-set-factory.test.ts
test/transports/routing.test.ts
test/transports/sse.test.ts
test/transports/websocket.test.ts
test/validation.test.ts

[PDI-26](https://smartcontract-it.atlassian.net/browse/PDI-26)
This PR adds/modifies tests to increase test coverage. It also refactors few files to get rid of bugs and type issues. 
So far with the tests in this PR coverage report is following 
**99.28%** Statements and lines (97.45% currently)
**95.34%** Branches (92.75% currently)
**100%** Functions  (96.24% currently)
[PDI-26]: https://smartcontract-it.atlassian.net/browse/PDI-26?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add missing tests to increase test coverage

---

src/config/index.ts
src/validation/index.ts

Calculate feed ID after overriden values to make it consistent

---

.github/workflows/main.yaml
test/validation.test.ts

[PDI-1957](https://smartcontract-it.atlassian.net/browse/PDI-1957)
[PDI-1957]: https://smartcontract-it.atlassian.net/browse/PDI-1957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add gh workflow step to check for test.only()

---

src/cache/response.ts
src/util/logger.ts
test/cache/response-cache.test.ts
test/index.test.ts
test/validation.test.ts

[PDI-180](https://smartcontract-it.atlassian.net/browse/PDI-180)
[PDI-180]: https://smartcontract-it.atlassian.net/browse/PDI-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

censor sensitive values when writing to response cache

---

src/cache/response.ts

[PDI-24](https://smartcontract-it.atlassian.net/browse/PDI-24)
[PDI-24]: https://smartcontract-it.atlassian.net/browse/PDI-24?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

warn when saving undefined to response cache

---

src/validation/index.ts
test/util.ts
test/validation.test.ts

Assign empty object to data is missing in request

Request data object validation

---

.github/workflows/open-version-bump-pr.yaml
README.md
package.json

- Added script to generate ref tables in package.json
- Added step in version bump PR workflow to run ref table generation script
- Updated README links to docs
- Minor linting fixes

PDI-32: Add step to version bump PR workflow to add generated docs

---

src/transports/websocket.ts
test/transports/websocket.test.ts

- added 1000 as the argument for the close method on a wsConnection
- added a test to verify the correct ws closed connection code

patch/PDI-2106: Change WS closing status to 1000

---

test/util.ts

- getMetrics method now accesses metrics directly

patch/PDI-2104: getMetrics method now accesses metrics directly

---

src/adapter/price.ts
src/adapter/stock.ts

[PDI-2105](https://smartcontract-it.atlassian.net/browse/PDI-2105), [PDI-2139](https://smartcontract-it.atlassian.net/browse/PDI-2139)
[PDI-2105]: https://smartcontract-it.atlassian.net/browse/PDI-2105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PDI-2139]: https://smartcontract-it.atlassian.net/browse/PDI-2139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add StockEndpoint and ForexPriceEndpoint

---

src/cache/local.ts
src/metrics/index.ts
src/transports/http.ts
test/metrics/metrics.test.ts

- Added http request count per background execute metric
- Added local cache overflow count metric

Add new metrics for runbook

---

.github/workflows/pinned-dependencies.yaml

- will be needed once cache lock PR is merged

added redlock beta version to regex for acceptable pinned deps

---

src/transports/websocket.ts

Allows for the WS connection options to be derived from the desired subscriptions

Provide WebSocket options func with desired subscriptions

---

src/transports/websocket.ts

The new type logs URL changes at debug level rather than info since frequent changes are expected.
https://smartcontract-it.atlassian.net/browse/DF-19232

DF-19232 set "Websocket url has changed" log to debug

---

scripts/generator-adapter/generators/app/templates/src/transport/custom.ts.ejs

Removed generic `T` from custom transport template in ea generator script.

change types in custom transport template

---

README.md
docs/components/transport-types/streaming-transport.md
docs/components/transport-types/subscription-transport.md
docs/components/transports.md
docs/guides/creating-a-new-v3-ea.md

Added docs for Streaming and Subscription transports
Fixed EA generation command in Creating A New Adapter doc

add docs for abstract transports

---

src/transports/websocket.ts

- Will aid in debugging WS connection issues

Make WS Error on connection a Warn log, rather than Debug

---

src/adapter/basic.ts
src/adapter/endpoint.ts
src/adapter/lwba.ts
src/adapter/types.ts
src/index.ts
src/metrics/constants.ts
src/validation/error.ts
src/validation/input-params.ts
test/lwba.test.ts

- Add customOutputValidation to allow custom validation rules in endpoints. 
- Update LWBAEndpoint with customOutputValidation to validate bid/mid/ask

Add customOutputValidation

---

src/adapter/por.ts

For https://sepolia.etherscan.io/address/0xdC8F09CEb7FF5ba61A2aaDCb3058Cb24D2926b01#code

Add types for PoRTokenAddress

---

scripts/generator-adapter/generators/app/index.ts
src/metrics/index.ts

To align with what most other EAs are using
Also replaced a deprecated method

Bump generator version

---

package.json

Mostly dependency version bumps

Bump version to 1.7.2

---

src/config/index.ts

https://smartcontract-it.atlassian.net/browse/DF-21033

Mask RPC URl

---

test/validation.test.ts

I noticed a test which flaked because it assumes that `new Date().getTime()` returns the same value throughout the test.
Use a fake clock in the test so it doesn't change during the test.

Fix flaky test with fake clock

---

scripts/generator-adapter/generators/app/index.ts

This command is for some reason not working on my local env but it seems to be working on GHA

Fix new adapter generator
