smartcontractkit/ea-framework-js

- src/adapter/basic.ts
- src/index.ts
Metrics were getting initialized after Redis cache which uses metrics on open and retry connection. Moved metrics initialization before adapter dependency initialization.
Issue brought up [here](https://chainlink-core.slack.com/archives/C01URRHMM35/p1674174256335479?thread_ts=1674171364.273049&cid=C01URRHMM35)
> Initialize metrics earlier

- src/adapter/basic.ts
- src/adapter/price.ts
- src/cache/index.ts
- src/cache/local.ts
- src/cache/redis.ts
- src/cache/response.ts
- test/util.ts
- Marked values as readonly for cache get/set to avoid unexpected updates outside of cache
- Clone response for inverses prior to setting inverse result
> Fix inverse data issue

- src/transports/http.ts
- src/transports/websocket.ts
We used to export ProviderRequestConfig previously, now we don't. This PR we don't don't export.
It helps typing EAs.
> Export ProviderRequestConfig & WebsocketTransportGenerics

- src/adapter/basic.ts
- src/config/provider-limits.ts
- src/transports/websocket.ts
- test/metrics/ws-metrics.test.ts
- test/transports/http.test.ts
- test/transports/websocket.test.ts
The websocket background execute doesn't sleep when there are no new subs and there is no established connection. This causes the logs to get flooded with statements every 1ms making it hard to debug any issues.
> Fix excessive debug/trace logging

- src/cache/index.ts
- test/cache/cache-key.test.ts
Changing max key length logic from truncating string to hashing it. Now that the requester is using the same logic to generate keys for the request queue, keys were regularly exceeding the max due to batch requests.
> Update max key length logic

- docs/v3-ea-components/transport-types/routing-transport.md
- src/transports/meta/routing.ts
- test/transports/routing.test.ts
The default transport shouldn't be set in the routing transport class, because it would cause problems with cache keys. The default should be set in the input parameters instead.
> Remove defaultTransport parameter from RoutingTransport

- src/adapter/price.ts
- test/price.test.ts
With the change in logic to move `requestTransforms` to endpoints, the includes transform was limited to just PriceEndpoints. Previously when it was at the adapter level, every requests were being transformed to include `priceMeta`. Now that only PriceEndpoints have this transformation, basic AdapterEndpoints do not meaning they would not have the `priceMeta` field. The current logic was throwing errors due to this so this change marks the field as optional.
> Mark priceMeta as optional

- src/adapter/basic.ts
- src/adapter/endpoint.ts
- src/adapter/types.ts
- src/background-executor.ts
- src/transports/index.ts
- test/transports/routing.test.ts
There is a problem with the way the transport routes were declared and passed as parameters in the current version of the framework. The `AdapterEndpoint` specifies the transport as `Record<string, Transport<T>`, but in cases where we have different transport types, the type of the `Provider` property of the generics would be different, and the compiler would not like this (because it would attempt to give T a concrete type, and there would be different alternatives to use).
This PR delegates this typing resolution to a separate class, that will perform a simpler check by the use of a builder pattern.
> Refactor transport routes

- src/background-executor.ts
- src/config/index.ts
- src/metrics/index.ts
- src/transports/websocket.ts
- src/util/index.ts
- test/background-executor.test.ts
- test/transports/websocket.test.ts
This PR attempts to mitigate issues found with v3 EAs, primarily websocket ones (DAR, Galaxy). Those EAs work perfectly for a period of time, then suddenly we can observe the background executions drop to zero. This means one of two things:
- **The background execution loop is crashing.** This seems very unlikely to be the culprit because there's no logs to this end, and one would expect them (things like unhandled promises). I have verified that some output would be present by simply throwing an exception manually from the loop, and it results in both a very clear log message and the process exiting.
- **The background execution loop is stuck.** This is the current best guess. If an issue were happening in the background execution, looking at the current logic that is in the deployed …
> Add background execute and websocket open timeouts

- package.json
- src/adapter/basic.ts
- src/adapter/price.ts
- src/adapter/types.ts
- src/config/index.ts
- src/index.ts
- test/transports/routing.test.ts
- test/util.ts
The refactor of the adapter generics worked pretty well, but there was one problem: the `Adapter` class itself used the config as a type, instead of taking advantage of the new classes to rely on simpler types. This PR changes the adapter basic generics to use the settings definitions instead.
> Fix settings generics in adapter

- docs/v3-ea-components/tests.md
- src/transports/websocket.ts
- src/util/index.ts
- test/background-executor.test.ts
- test/metrics/ws-metrics.test.ts
- test/transports/routing.test.ts
- test/transports/websocket.test.ts
- test/util.ts
This hadn't surfaced as an issue yet, but there was a potential problem in the code: the open handler that the transport will use exposes the entire WS connection to the user. This is great for extensibility and allows for custom login flows for example, but if the user were to, say, completely replace all listeners from this function, it could affect the logic of the websocket transport itself. This PR changes how those listeners are set up, and the connection flow, as follows:
- Connection is created
- Open listener is registered (which will call the user handler)
- User can do whatever in their handler, including setting up new listeners
- The user handler resolves or rejects
- All listeners are removed, and the rest of the transport listeners are added (message, error, close)
> Reorganize WebSocket listeners

- src/cache/metrics.ts
- src/cache/redis.ts
- src/metrics/index.ts
- src/transports/abstract/subscription.ts
- src/util/subscription-set/redis-sorted-set.ts
- src/util/subscription-set/subscription-set.ts
- src/validation/index.ts
- test/subscription-set/redis-subscription-set.test.ts
- test/subscription-set/subscription-set-factory.test.ts
- Added transport name to the redis subscription set key to help avoid subscription sets being shared between transports of the same endpoint
- Added redis metrics to the redis subscription set
> Add transport name and metrics to redis subscription set

- src/transports/websocket.ts
- test/transports/websocket.test.ts
Moved setting new subscriptions to the open connection block. This accounts for the scenario that the connection is closed on the server side.
> Fix resubscribes on server side ws connection closures

- src/adapter/basic.ts
- test/adapter.test.ts
[PDI-1955](https://smartcontract-it.atlassian.net/browse/PDI-1955)
I want to note that i was not able to reproduce this issues. Typescript was always complaining about name being lowercase 
[PDI-1955]: https://smartcontract-it.atlassian.net/browse/PDI-1955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> enforce uppercase ea name

- src/cache/redis.ts
- test/cache/response-cache.test.ts
- test/index.test.ts
- test/util.ts
Redis functions is only available starting version 7. Not all NOPs are running Redis 7 and some cannot since it isn't available for Azure or GCP. The implementation was updated so that it does not use functions but still leverages custom scripting. The new implementation still leverages server side caching to maintain performance.
> Update custom script to avoid using redis functions

- src/adapter/basic.ts
- test/rate-limit-config.test.ts
Added a check in adapters/basic.ts for non-positive numbers in rate limit tiers. The framework now throws an error on startup if the rate limit value is not a positive number.
Also added a test in test/rate-limit-config.test.ts.
> PDI 2010 - Added rate limit config validations for non-positive numbers in v3 framework

- src/validation/utils.ts
- test/validation.test.ts
Some data providers indicated timestamps are slightly ahead due to clock drift causing logs to get filled with response timestamp warnings. The validator was adjusted to allowed timestamps up to 50ms over the current time in the adapter.
> Adjust response timestamp validator to account for clock drift

- src/validation/input-params.ts
- test/validation.test.ts
- Fixed default value check not allowing 0 for number types
- Changed array validation logic to return the same value as passed in request. `undefined` doesn't return empty array.
- Potentially up for discussion if we should change the behavior to this but I'd argue to maintain what it was before. Existing falsy checks on array request params would start failing (i.e. `if (req.addresses)`)
> Fix input validator 0 defaults

- .c8rc.json
- .github/workflows/main.yaml
- .github/workflows/open-version-bump-pr.yaml
- README.md
[PDI-144](https://smartcontract-it.atlassian.net/browse/PDI-144)
This PR adds two badges to readme, `npm version` and `code coverage`.  
`npm version` is straightforward. Given npm package name, the latest published version will be automatically shown. 
For the `code coverage` badge there are some additional changes. Since we don't store coverage result in third party service like codecov we need to 'manually' update the coverage percentage in README. New workflow step is added to _open-version-bump-pr.yaml_  to automate that process. 
1. Once the tests have been completed and coverage result is available a new step in main workflow will commit coverage result  file in a temporary branch. This is workaround since it is not possible to share files between workflows and we don't want to run …
> add badges to readme

- .github/workflows/main.yaml
The PR fixes a bug where after PR merging to base branch, the `main` workflow was creating another 'coverage-pr-' branch. Now it makes sure that PR number is available and only then creates tmp coverage branch.
> fix bug with empty coverage branch

- .github/WORKFLOW-README.MD
- .github/workflows/open-version-bump-pr.yaml
[PDI-2099](https://smartcontract-it.atlassian.net/browse/PDI-2099)
This PR changes the logic for version-bump pr workflow. Previously each different labeled PR merges would create different Version bump PRs. For example given current version of 1.0.0, PR `A` labeled as `major` and PR `B` labeled as `patch` after the merge would create two version bump PRs, `version-bump/2.0.0-main` and `version-bump/1.0.1-main` respectively.
With the new logic a PR merge would create  just one version bump PR from  'version-bump' branch. In this case if other PRs are merged it will compare the versions and update the version bump PR if there is higher version change. 
The same example now. Given current version of 1.0.0, PR `A` is labeled as `major` and PR `B` labeled as `patch`. If `A` is merged first, …
> change the logic of version-bump pr workflow

- src/adapter/basic.ts
- test/index.test.ts
- Framework now throws an error if an EA is not in reader-writer mode while the cache type is set to local
- Added test for this check
> PDI-63: Add startup check to verify that cache type is shareable when not setting EA to RW

- src/util/testing-utils.ts
- test/adapter.test.ts
- test/background-executor.test.ts
- test/cache/cache-key.test.ts
- test/cache/helper.ts
- test/cache/local.test.ts
- test/cache/redis.test.ts
- test/cache/response-cache.test.ts
- test/correlation.test.ts
- test/error.test.ts
- test/index.test.ts
- test/logger.test.ts
- test/metrics/metrics.test.ts
- test/metrics/polling-metrics.test.ts
- test/metrics/redis-metrics.test.ts
- test/metrics/warmer-metrics.test.ts
- test/metrics/ws-metrics.test.ts
- test/overrides.test.ts
- test/price.test.ts
- test/rate-limit-config.test.ts
- test/subscription-set/redis-subscription-set.test.ts
- test/subscription-set/subscription-set-factory.test.ts
- test/transports/http.test.ts
- test/transports/routing.test.ts
- test/transports/sse.test.ts
- test/transports/websocket.test.ts
- test/validation.test.ts
This PR moves `test/utils.ts` file to `src/util/testing-utils.ts` and updates all the references. The change is required so that the testing utils are exported and can be used in EA integration tests in monorepo. 
The new `src/util/testing-utils.ts` is set to be excluded from testing coverage since the previous file was never part of a coverage and the functions in the file are used only in tests, not in src.
> move test utils to src

- src/adapter/basic.ts
- src/background-executor.ts
- src/cache/index.ts
- src/cache/local.ts
- src/cache/redis.ts
- src/cache/response.ts
- src/config/index.ts
- src/index.ts
- src/metrics/index.ts
- src/transports/abstract/streaming.ts
- src/transports/abstract/subscription.ts
- src/transports/http.ts
- src/transports/websocket.ts
- src/util/logger.ts
- src/util/requester.ts
- src/validation/error.ts
- src/validation/index.ts
- Added an optional CENSOR_SENSITIVE_LOGS setting that defaults to false
- If set to true, sensitive logs will not be run
Linked ticket: https://smartcontract-it.atlassian.net/browse/PDI-2152
> (workaround) Put logs that would expose the input parameters object behind a feature flag

- src/metrics/index.ts
- src/validation/index.ts
- test/metrics/labels.test.ts
[PDI-226](https://smartcontract-it.atlassian.net/browse/PDI-2226)
This PR fixes bug with status_code property of http metrics where it  was 200 while response from EA was 4xx. Now the status_code will be the same as response status code if there are no errors.
> fix status_code for metrics

- src/adapter/basic.ts
- src/adapter/types.ts
- src/util/logger.ts
- test/custom-logger.test.ts
- test/metrics/feed-id.test.ts
- test/subscription-set/subscription-set-factory.test.ts
Once crucial piece of the EA framework is its logger, used consistently and often throughout the code. Due to the potential for applications that use the framework needing to conditionally modify or filter logs, this PR changes the current implementation to keep a static reference to a logger factory and defers the actual instancing until the first time a child logger is called.
Originally this was planned to be solved by implementing a Dependency Injection framework across all the code, but I've chosen to go with this approach to minify the impact to the current logic. From my research into the current alternatives (tsyringe, inversifyjs, typedi, etc) most of them use Decorators, which are still in an experimental stage and can be painful to work with once the codebase gets large enough.
> Allow logger injection

- src/transports/websocket.ts
* Include the endpoint context in the WebSocket `subscribeMessage` and `unsubscribeMessage` handlers. 
* This allows WS endpoints to support more complex subscription messages, such as using a default exchange symbol from the adapter settings.
> Include endpoint context in WS subcribe/unsubscribe builders

- src/adapter/endpoint.ts
- src/adapter/types.ts
- src/validation/index.ts
* Provide requestTransform's with adapter settings.
* This is useful in situations where the adapter should transform requests differently based on the adapter settings, e.g. picking a different default exchange to fetch data for.
> Provide requestTransform's with adapter settings.

- src/adapter/basic.ts
- src/cache/redis.ts
- src/config/index.ts
- src/index.ts
- src/util/testing-utils.ts
- test/cache/cache-lock.test.ts
- test/index.test.ts
- Ran into an issue in staging with the cache lock. When adapters are updated, new pods are spun up and the old ones don't close until the new ones are ready via a health check. This causes the second adapter to try and fail to acquire the cache lock.
- Now, by default there is a 60 second delay before an adapter tries to acquire the lock while the rest of the adapter startup continues as usual. This allows the second adapter to pass its health check, cause the first one to close, and then make it possible for the second adapter to acquire the lock.
> Cache lock fix: deferring lock acquisition

- src/cache/factory.ts
- src/cache/redis.ts
- test/cache/cache-lock.test.ts
- test/cache/redis.test.ts
- test/index.test.ts
- test/metrics/redis-metrics.test.ts
[PDI-68](https://smartcontract-it.atlassian.net/browse/PDI-68)
This PR modifies redis cache logic so that cache entries are not only stored in redis, but also in a local cache. It also changes the read logic so that it tries to get the value from local cache first and only if it doesn't exist it tries to get the value from redis. This will improve the reads if the cache type is redis since for most of the time reads will be from local cache.  The only time when we will need to actually read from redis is when EA restarts with cached values in redis. 
[PDI-68]: https://smartcontract-it.atlassian.net/browse/PDI-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add local cache to redis

- src/adapter/por.ts
Set `API_TIMEOUT` default for a PoR adapter to the max value
> Add API_TIMEOUT default to the PoR adapter subclass

- scripts/generator-adapter/generators/app/templates/src/endpoint/base.ts.ejs
- src/validation/input-params.ts
- test/validation.test.ts
Added second optional argument to InputParameters constructor. It will hold the examples value and ensure that provided examples use correct values in terms of types. 
Input parameter examples are not directly used in framework and are mainly needed for monorepo to generate example requests for Readme files. 
The EA generator will be updated once changes in this PR are deployed to npm
> add examples to input parameters

- scripts/generator-adapter/generators/app/templates/src/endpoint/base.ts.ejs
This PR modifies `base.ts.ejs` template so that newly generated EAs will have input examples
> add input examples to ea generator

- src/adapter/por.ts
Set `CACHE_MAX_AGE` default to 360s in the PoR subclass. Otherwise the cache could expire before the next background execute cycle runs if it takes almost the full 180s to process.
> Add CACHE_MAX_AGE default to the PoR subclass

- package.json
- yarn.lock
This is mostly needed to update individual EAs that use axios in monorepo
> bump axios to 1.6.0

- src/cache/index.ts
- src/cache/local.ts
- src/cache/redis.ts
- src/util/testing-utils.ts
- test/cache/local.test.ts
- test/cache/redis.test.ts
This PR is part of [DF-19487](https://smartcontract-it.atlassian.net/browse/DF-19487)
Added a new `setTTL()` function to the cache interface that updates the time to live value for a key. 
[DF-19487]: https://smartcontract-it.atlassian.net/browse/DF-19487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added setTTL function to cache

- src/adapter/por.ts
[DF-19638](https://smartcontract-it.atlassian.net/browse/DF-19638)
Added new types for new `PoRProviderEndpoint`. `PoRProviderEndpoint` enforces the response of the endpoint to have `result` and `ripcord` properties
[DF-19638]: https://smartcontract-it.atlassian.net/browse/DF-19638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added PoRProvider types

- src/adapter/endpoint.ts
- src/util/types.ts
- src/validation/index.ts
- test/transports/routing.test.ts
[DF-19825](https://smartcontract-it.atlassian.net/browse/DF-19825)
Added a support for providing override for `transport` input parameter. Somewhat similar to symbol overrides, the value of the transport can be changed if provided in the request. 
Syntax is the same as with symbol overrides, but to override the transport `transport` is used with a value of transport
```json
{
"data": {
"base": "ETH",
"quote": "USD",
"transport": "ws",
"overrides": {
"tiingo": {
"ETH":"ethereuem",
"transport": "rest"
}
}
} 
}
```
In this example although the transport is set to `ws` in the request body, since there is an override, the `rest` transport will be used. 
Some notes on the changes. 
1. The keyword and placement of the override. 
Alternatively the key can be outside overrides object, most likely …
> Added support for transport overrides

- .github/actions/setup/action.yaml
- .github/workflows/add-or-validate-labels.yaml
- .github/workflows/main.yaml
- .github/workflows/open-version-bump-pr.yaml
- .github/workflows/pinned-dependencies.yaml
- .github/workflows/publish.yaml
Description
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
Updated all GH actions to newer versions that support Node20
> Chore/update GitHub actions

- .github/workflows/open-version-bump-pr.yaml
- Seeing failures due to `unexpected override existing field under "ref"`: https://github.com/smartcontractkit/ea-framework-js/actions/runs/9420850499/job/25953763992
- I _think_ this is due to a badly formed command for creating the new branch, so testing the fix here.
> Fix creating a new branch in version bump workflow

- .github/workflows/main.yaml
- .github/workflows/pinned-dependencies.yaml
- src/background-executor.ts
- src/config/index.ts
- src/metrics/index.ts
- src/transports/abstract/streaming.ts
- src/transports/abstract/subscription.ts
- test/transports/websocket.test.ts
- Add configurable `STREAM_HANDLER_RETRY_MIN_MS`, `STREAM_HANDLER_RETRY_MAX_MS` and `STREAM_HANDLER_RETRY_EXP_FACTOR` for exponential retries for subscription handlers. Default to `100ms * 3^retryCount` (100ms, 300ms, ~1s, 3s, 8s, 24s, ..., 20m) 
- Remove commented config vars that don't seem to be used at the moment
> Introduce exponential backoff for subscription errors

- src/config/index.ts
- src/transports/http.ts
Previously
```
"errorMessage": "Provider request failed with status undefined: \"[object Object]\"",
```
Now
```
"errorMessage": "Provider request failed with status undefined: \"{\"message\":\"Forbidden\"}\"",
```
> Improve error messaging

- src/util/subscription-set/subscription-set.ts
[DF-20406](https://smartcontract-it.atlassian.net/browse/DF-20406)
[DF-20406]: https://smartcontract-it.atlassian.net/browse/DF-20406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added prefix support for redis subscription set key

- scripts/generator-adapter/generators/app/templates/src/transport/customfg.ts.ejs
Removed writing to a cache in a `foregroundExecute` transport template. 
foregroundExecute should not be used generally, but it's intended for simple request-response type of transports. If we cache the value before returning, the value might become stale during the duration of cache TTL. By removing it the transport's code will be executed on every request.
> Removed caching from fg transport template

- src/cache/index.ts
- src/cache/response.ts
TP and ICAP now comes from a single EA, causing confusion on dashboard: https://chainlink-core.slack.com/archives/C02FM5ZP2TC/p1728310901092909?thread_ts=1724330144.138549&cid=C02FM5ZP2TC
The metric comes from `adapterName` here we override this value based on EA param `adapterNameOverride`
> Override meta.adapterName

- src/adapter/endpoint.ts
- src/adapter/types.ts
- test/overrides.test.ts
https://smartcontract-it.atlassian.net/browse/DF-20277
Currently single EA can only read override from a single name, for example `cfbenchmarks` and `cfbenchmarks2` can only read override for `cfbenchmarks`. This causes issues on feed where we want to use both but they each have different override values
Leverage `adapterNameOverride` input param, this param is already used to override metric name on response. Here we try to read override from `adapterNameOverride` first, if not available, read from `this.adapterName`, maintaining backward compatibility
There is no limit on how to define this override, you can
- Put it in as a regular param
- Hard-code it in adapter code: [example](https://github.com/smartcontractkit/external-adapters-js/pull/3528/files)
- Put it in env variable
> Allow EA to read from override of another name

- src/adapter/por.ts
Use chainId instead of network
The upstream does not have a consistent network naming, hence we will use chainid instead
> Add chainId to PoRTokenAddress

- src/util/logger.ts
https://stackoverflow.com/questions/71938587/unable-to-determine-transport-target-for-pino-pretty
For some reason it is now throwing error in deployments after version bump
> Fix logging

- src/util/requester.ts
Log the actual HTTP call for easier debugging in the future
> Log HTTP request

- src/util/logger.ts
[DF-20316](https://smartcontract-it.atlassian.net/browse/DF-20316)
Updating logger timestamps to include both epoch time and human readable (ISO) time
[DF-20316]: https://smartcontract-it.atlassian.net/browse/DF-20316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DF-20316 add isoTime to standard log line as human readable timestamp

- src/metrics/index.ts
- src/transports/websocket.ts
We should be able to monitor the WS connection attempt metric as necessary to understand if the EA request rate against a provider WS endpoint is within expected ranges
> add websocket connection attempt metric

- src/adapter/price.ts
- test/price.test.ts
DF 20953 - RWA updates- Disable includes.json files affects for endpoint:crypto/ crypto_lwba aliases
https://smartcontract-it.atlassian.net/browse/DF-20953
> Disable includes.json files affects for endpoint:crypto/ crypto_lwba aliases

- src/transports/websocket.ts
- test/transports/websocket.test.ts
Add option to declare websocket handlers for close + error events
> WS close error handlers

- package.json
I found that trying to run tests when there are type errors, gives very unhelpful errors:
```
$ yarn test test/transports/routing.test.ts
yarn run v1.22.22
$ EA_HOST=localhost LOG_LEVEL=error EA_PORT=0 c8 ava test/transports/routing.test.ts
Uncaught exception in test/transports/routing.test.ts
TSError {
diagnosticCodes: [
7006,
],
}
✘ test/transports/routing.test.ts exited with a non-zero exit code: 1
─
1 uncaught exception
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
error …
```
> Compile tests before running

- scripts/generator-adapter/generators/app/index.ts
https://github.com/smartcontractkit/ea-framework-js/pull/433 added logic to output errors from the `yarn install` command in the adapter generator. But they way it detected an error was wrong and this wasn't noticed because the flow as broken because of a missing npm package.
Now that the npm package issue is fixed, it turns out the example generator still fails because of the incorrect check.
If the command succeeds, there is no `error` response, so we can't check its error code.
Check for the presence of the `error` rather than the value of the `error.code`.
`generate-example-adapter` now passes on CI.
I also ran
```
git clean -df
yarn build
path_to_generator="$(pwd)/dist/src/generator-adapter/generators/app/index.js"
DEBUG=* yo "$path_to_generator" examples
cd examples/example-adapter …
```
> Fix error check in example generator

- test/overrides.test.ts
https://github.com/smartcontractkit/ea-framework-js/pull/283 added the possibility of specifying a different adapter name to use (via `adapterNameOverride ` on the request context) as a key for request overrides.
The way this is implemented, if `adapterNameOverride` is used to specify a different adapter name, but no overrides are provided for that name, but overrides *are* provided for the real adapter name, then those overrides are used instead.
This could be surprising and/or intended, but it is not covered by unit tests so it could be accidentally changed without us realizing which could be a breaking change.
Added a unit test for the case where no overrides are given for the `adapterNameOverride` name but overrides are given for the real adapter name.
> Add extra test for overrideAdapterName

- src/adapter/endpoint.ts
- src/util/index.ts
- test/overrides.test.ts
- test/transports/routing.test.ts
- test/utils.test.ts
[DF-21153](https://smartcontract-it.atlassian.net/browse/DF-21153)
The name of an adapter can refer to 2 different things:
1. The name of the package that implements the adapter
2. The name field in the definition of the adapter.
These are typically (but not necessarily) related but there are difference:
1. The package name is typically lower case while the name field is required to be upper case.
2. The package name typically uses a hyphen as separator while the name field typically uses an underscore as separator.
See for example the [name field](https://github.com/smartcontractkit/external-adapters-js/blob/cb6a8a287e311fd17697810c0accd2e2a093e43b/packages/sources/blocksize-capital/src/index.ts#L7) of the `blocksize-capital` adapter which has value `BLOCKSIZE_CAPITAL`.
This causes …
> Allow hyphen in override adapter name

- src/util/group-runner.ts
- src/util/index.ts
- test/util/group-runner.test.ts
In https://github.com/smartcontractkit/external-adapters-js we have at least 5 different places where we limit the number of concurrent RPCs:
1. [dlc-btc-por](https://github.com/smartcontractkit/external-adapters-js/blob/8ebcbd74baaa377344fcceb900ddd880e8fc3165/packages/sources/dlc-btc-por/src/transport/proof-of-reserves.ts#L99-L115)
2. [eth-beacon](https://github.com/smartcontractkit/external-adapters-js/blob/8ebcbd74baaa377344fcceb900ddd880e8fc3165/packages/sources/eth-beacon/src/transport/balance.ts#L127-L139)
3. [polkadot-balance](https://github.com/smartcontractkit/external-adapters-js/blob/8ebcbd74baaa377344fcceb900ddd880e8fc3165/packages/sources/polkadot-balance/src/transport/balance.ts#L81-L97)
4. [por-address-list](https://github.com/smartcontractkit/external-adapters-js/blob/8ebc …
> Add GroupRunner to limit concurrent RPCs

- src/util/testing-utils.ts
- test/util/testing-utils.test.ts
When writing unit tests it can be useful to pass stub objects.
If a field is missing on such a stub, it will be `undefined`, which then might cause confusing errors later.
So it's useful to know which fields are being accessed to be able to provide them proactively.
This PR adds a `makeStub` testing utility which wraps an object in a `Proxy` and throws an error if an absent property is accessed on object.
> Add makeStub testing util

- package.json
- src/adapter/types.ts
- src/transports/sse.ts
- yarn.lock
The [renovate PR](https://github.com/smartcontractkit/ea-framework-js/pull/347) to update `@types/eventsource` to v3 had failures.
While investigating I found that @types/eventsource was [removed](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71870) because the types are included in `eventsource` starting from version 3.0.0.
1. Ran `yarn remove @types/eventsource`.
2. Ran `yarn add eventsource`.
3. Fixed import statements.
4. Changed `EventSource.EventSourceInitDict` to `EventSourceInit`
5. Removed `^` from version after `pinned-dependencies.yaml` failed.
> Update dependency eventsource from 2.0.2 to 4.0.0 and remove @types/eventsource
